package database

const ticketTable = `CREATE TABLE IF NOT EXISTS tickets(
	id SERIAL PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	category VARCHAR(50) NOT NULL,
	description VARCHAR(300) NOT NULL,
	status VARCHAR(50) NOT NULL,
	client INT REFERENCES users(id) ,
	assign INT REFERENCES users(id) ,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)`

const userTable = `CREATE TABLE IF NOT EXISTS users(
	id SERIAL PRIMARY KEY,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR NOT NULL,
	type VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

)`
